# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
StyLua = "JohnnyMorganz/StyLua@2.0.2"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.28.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.43.0"
lune = "lune-org/lune@0.8.9"
darklua = "seaofvoices/darklua@0.16.0"

