std = "selene-std+luau"
exclude = ["dist/**", ".lune/**"]

[lints]
global_usage = "allow"
multiple_statements = "allow"
unused_variable = "allow"
shadowing = "allow"
incorrect_standard_library_use = "allow"