[package]
name = "tracyspells/teisu"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "Reactive library for Roblox"
repository = "https://github.com/tracyspells/teisu"
homepage = "https://tracyspells.github.io/teisu/"
exclude = ["**"]
include = ["lib", "lib/**/*.luau", "wally.toml", "default.project.json", "LICENSE"]
private = true
