return {
    package = {
        description = "Reactive library for Roblox",      
        exclude = { "**" },
        homepage = "https://tracyspells.github.io/teisu/",
        include = {
            "lib",
            "lib/**/*.luau",
            "wally.toml",
            "default.project.json",
            "LICENSE",
        },
        license = "MIT",
        name = "tracyspells/teisu",
        private = true,
        realm = "shared",
        registry = "https://github.com/UpliftGames/wally-index",
        repository = "https://github.com/tracyspells/teisu",
        version = (nil :: any) :: string,
    }
}