name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install packages
        run: wally install

      - name: Publish Wally package
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          wally publish
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}

      - name: Build package
        run: rojo build --output teisu.rbxm

      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.release }}
        with:
          files: teisu.rbxm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}