name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Build needed files
        run: |
          mkdir -p dist 
          lune run regen
          lune run build
          lune run publishing
      
      - name: Login to Wally
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: wally login --token "$WALLY_AUTH"

      - name: Publish package to Wally
        run: wally publish -v --project-path dist/

      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.release }}
        with:
          files: dist/teisu.rbxm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}